### PR TITLE
IOS compilation error with version 14 x x

### LINKED ISSUE #159: [Bug]: iOS Compilation error with version 0.14.3
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i update to 0.14.3, i clean flutter and iOS

When building the project, I'm getting the following error messages:

Cannot convert value of type '[AppEvents.ParameterName : Any]' to expected argument type '[String : Any]'

Cannot convert value of type '[AppEvents.ParameterName : Any]' to expected argument type '[String : Any]'

problem is on this code: (SwiftFacebookAppEventsPlugin)

`  private func handleLogEvent(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        let arguments = call.arguments as? [String: Any] ?? [String: Any]()
        let eventName = arguments["name"] as! String
        let parameters = arguments["parameters"] as? [AppEvents.ParameterName: Any] ?? [AppEvents.ParameterName: Any]()
        if arguments["_valueToSum"] != nil && !(arguments["_valueToSum"] is NSNull) {
            let valueToDouble = arguments["_valueToSum"] as! Double
            AppEvents.logEvent(AppEvents.Name(eventName), valueToSum: valueToDouble, parameters: parameters)
        } else {
            AppEvents.logEvent(AppEvents.Name(eventName), parameters: parameters)
        }
`

### Expected Behavior

Build should be successful.

### Steps To Reproduce

Using Xcode 13.1, flutter version 2.2.3:

### Platform

iOS

### Flutter Doctor

```shell
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.6 20G165 darwin-x64, locale en-FR)
    • Flutter version 2.2.3 at /Users/mac/development/flutter
    • Framework revision f4abaa0735 (4 months ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mac/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 95.0.4638.69
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!
```

### LINKED ISSUE #171: [Bug]: Cannot compile for iOS due to error "Undefined symbols for architecture arm64"
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When adding facebook_app_events to our app, we are getting these warnings and errors. 

```
ld: warning: argument missing after -rpath
    ld: warning: Could not find or use auto-linked library 'swiftFileProvider'
    ld: warning: Could not find or use auto-linked library 'swift_Concurrency'
    ld: warning: Could not find or use auto-linked library 'swiftDataDetection'
    ld: warning: Could not find or use auto-linked library 'stdc++'
    ld: warning: Could not find or use auto-linked framework 'AVFAudio'
    ld: warning: Could not find or use auto-linked framework 'DataDetection'
    Undefined symbols for architecture x86_64:
      "_swift_FORCE_LOAD$_swiftDataDetection", referenced from:
          _swift_FORCE_LOAD$swiftDataDetection$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
         (maybe you meant: _swift_FORCE_LOAD$swiftDataDetection$_FBAudienceNetwork)
      "OBJC_CLASS$_SKAdImpression", referenced from:
          objc-class-ref in FBAudienceNetwork(FBAdSKAdNetworkManager.m.o)
      "_swift_FORCE_LOAD$_swiftFileProvider", referenced from:
          _swift_FORCE_LOAD$swiftFileProvider$_FBAudienceNetwork in FBAudienceNetwork(FBAudienceNetwork.o)
         (maybe you meant: _swift_FORCE_LOAD$swiftFileProvider$_FBAudienceNetwork)
    ld: symbol(s) not found for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

When we remove facebook_app_events from pubspec.yaml the project compiles just fine. 

### Expected Behavior

Adding the flutter facebook_app_events dependency should compile successfully for iOS.

### Steps To Reproduce

1. Add facebook_app_events: 0.14.5 to the pubspec.yaml
2. Build the project for iOS using XCode.

### Platform

iOS

### Flutter Doctor

```shell
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Mac OS X 10.15.7 19H15 darwin-x64, locale
    en-MT)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
[✓] Connected device (2 available)
```

### PR DESCRIPTION
**Pull request by suryaoddbit**
AppEvents.ParameterName.RawValue works on 12.0.2, so those who get version 12.0.0 when pod install will get an error. 
Close #159 
Close #171

### CODE REVIEW

**Review by DennisAlund — APPROVED** [review]

**Comment by viktor-savchik-idf** [comment]
@DennisAlund that's funny

**Comment by OneXeor** [comment]
@DennisAlund that's funny
